version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=Intrat_amoaman
      - DB_USERNAME=root
      - DB_PASSWORD=Bydaisscrea2000@

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: Intrat_amoaman
      MYSQL_ROOT_PASSWORD: Bydaisscrea2000@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
