include:
  - project: templates/ci-templates
    ref: main
    file:
       - build.yml
       - deploy-k8s-argocd.yml
       
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"      
      when: never
    - when: always

variables:
  HARBOR_PROJECT: "extranet"
  PROJECT_NAME: $CI_PROJECT_NAME
  SERVICE_VERSION: $CI_COMMIT_SHORT_SHA


stages:
  - build
  - deploy
  
build:
  stage: build

deploy:
  stage: deploy